spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
      show-sql: true
tlh:
  rms:
    db:
      url: <db-url>
      username: <your-db-password>
      password: <your-db-user>